package org.randoom.setlx.setlXMusic.midiSystem;

import org.jfugue.pattern.Pattern;

import javax.sound.midi.InvalidMidiDataException;
import java.io.IOException;

public interface iMidiManager {

    /**
     * Loads a pattern from a midi file.
     *
     * @param filename the filename, can also contain a path
     * @return A pattern that is generated by the *.mid-file.
     */
    Pattern load(String filename) throws IOException, InvalidMidiDataException;

    /**
     * Saves a {@link Pattern} to a midi file.
     *
     * @param filename
     */
    void save(String filename, Pattern pattern) throws IOException;


}
